# Generated by Django 5.2.8 on 2026-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department / Branch'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_daily_hours',
            field=models.IntegerField(default=6, verbose_name='Max Daily Teaching Hours'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Office Room Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof. Dr.', 'Prof. Dr.'), ('Doç. Dr.', 'Doç. Dr.'), ('Dr. Öğr. Üyesi', 'Dr. Öğr. Üyesi'), ('Öğr. Gör.', 'Öğr. Gör.'), ('Arş. Gör.', 'Arş. Gör.')], default='Prof. Dr.', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Teacher Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='off_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10, verbose_name='Off Day'),
        ),
    ]
