# Generated by Django 5.2.8 on 2026-07-29 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('title', models.CharField(blank=True, choices=[('Prof. Dr.', 'Prof. Dr.'), ('Doç. Dr.', 'Doç. Dr.'), ('Dr. Öğr. Üyesi', 'Dr. Öğr. Üyesi'), ('Öğr. Gör.', 'Öğr. Gör.'), ('Arş. Gör.', 'Arş. Gör.')], default='Prof. Dr.', max_length=50, null=True, verbose_name='Title')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department / Branch')),
                ('office_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Office Room Number')),
                ('off_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10, verbose_name='Off Day')),
                ('max_daily_hours', models.IntegerField(default=6, verbose_name='Max Daily Teaching Hours')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
